create  database employee;
use employee;
create table employee(EmpID int,EmpName varchar(20),DeptID int,Salary int,HireDate Date);
create table Department(DeptID int,DeptName varchar(20));
insert into  employee values(101,'john',1,50000,'2018-02-12'),(102,'alice',2,60000,'2019-07-10'),(103,'bob',1,55000,'2020-05-05'),(104,'carol',3,45000,'2017-09-20');
insert into Department values(1,'HR'),(2,'IT'),(3,'Sales');
select * from Department;
 select * from employee;
select EmpName, Salary from employee;
select EmpName, DeptName from employee e join Department d on e.DeptID = d.DeptID where d.DeptName = 'IT';
select * from employee where Salary > 50000;
select * from employee where HireDate < '2020-01-01';
select * from employee ORDER BY Salary DESC;
select COUNT(*) AS TotalEmployee from Employee;
select AVG(Salary) AS AverageSalary from employee;
 select DeptID, MAX(Salary) AS MaxSalary from Employee GROUP BY DeptID;
select DeptID, COUNT(*) AS EmployeeCount from Employee GROUP BY DeptID HAVING COUNT(*) > 1;
select * from employee where EmpName LIKE 'A%';
select * from employee where Salary BETWEEN 45000 AND 60000;
select e.EmpName, d.DeptName from employee e join Department d on e.DeptID = d.DeptID;
select e.EmpName, d.DeptName from employee e left join Department d on e.DeptID = d.DeptID;
select d.DeptName, COUNT(e.EmpID) AS EmployeeCount from Department d left join Employee e on d.DeptID = e.DeptID GROUP BY D.DeptName;
